config/routes.rb
Rails.application.routes.draw do
	namespace :admins do
		get 'products/new'
		root 'home#index'
  end
	resources :charges
	resources :purchase_record_products
	get "create", to: "purchase_record_products#create", as: :create_purchase_record_products
	resource :purchase_record
	resources :basket_products
	resource :basket
  resources :products
  devise_for :users
  root 'home#index'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text             not null
#  price       :integer          not null
#  unit        :string           default("yen"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  photo       :string
#  admin_id    :integer          default(0), not null
#

class Product < ApplicationRecord
	mount_uploader :photo, AvatarUploader
	serialize :avatars, JSON # If you use SQLite, add this line.
	include Hashid::Rails # hash id
	has_many :PurchaseRecordProducts, through: :purchase_record

	scope :has_admin_id_all, -> (current_admin_id) {
		where(admin_id: current_admin_id).ids
	}

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::Base
  def new
		@product = Product.new
	end
	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to root_path
		else
			render :new
		end
	end
	def show
		@product = Product.find(params[:id])
		@basket = Basket.find(current_user.id)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def new
		@product = Product.new
	end
	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to root_path
		else
			render :new
		end
	end
	def show
		@product = Product.find(params[:id])
		@basket = Basket.find(current_user.id)
	end


	private
		def product_params
			params.require(:product).permit(:name, :description, :price, :unit, :photo)
		end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/new.html.haml
%div.container.mx-auto
	%h1.text-center 新規商品の追加
	= simple_form_for(@product) do |f|
		= f.error_notification

		= f.input :name
		= f.input :description
		= f.input :price
		= f.input :unit, as: :select, collection: [['¥', 'yen', data: {unit: 'yen'}], ['$', 'dollar', data: {unit: 'dollar'}]]
		= f.input :photo
		= f.button :submit, class: "btn-block btn-info"

app/views/products/show.html.haml
%div.container.w-75.mx-auto.text-center
	.w-auto.mx-auto= image_tag @product.photo.to_s

	%div.card.mx-auto.w-75.text-left.my-5.p-4
		%h2.card-title.mb-4= @product.name
		%p.card-subtitle= @product.description
		%p.card-text= @product.price_unit

	= button_to "買い物かごに入れる", basket_products_path(product_id: @product.id, basket_id: @basket.id), class: "btn btn-info w-75 mb-5 py-3"